package com.bms.bookingService.dto;

public enum BookingEventType {
    BOOKING_INITIATED,
    SEATS_RESERVED,
    SEATS_RESERVATION_FAILED,
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    BOOKING_CONFIRMED,
    BOOKING_FAILED,
    BOOKING_CANCELLED,
    SEATS_RELEASED
}
